name: Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::005572111409:role/video-compiler-dev-gha-deploy
          aws-region: ap-south-1

      - name: Terraform Apply
        working-directory: infrastructure/terraform/envs/dev
        env:
          TF_VAR_github_repo: ${{ github.repository }}
          TF_VAR_llm_api_key: ${{ secrets.LLM_API_KEY }}
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false
